echo "#Architecture:" $(uname -a)
echo "#CPU physical :" $(nproc)
echo "#vCPU :" $(grep processor /proc/cpuinfo | wc -l)
echo "#Memory usage:" $(free --mega | awk 'NR == 2  {printf "%s/%sMB (%.2f%%)" ,$3,$2,$3/ $2100 }')
echo "#Disk Usage:" $(df -h --total | grep total |awk '{print $3 "/" $2 " (" $5 ")"}')
echo "#CPU load:" $(top -bn1 | awk 'NR == 3 { printf "%s" , $2 + $4 "%" }')
echo "#Last boot:" $(who -b | awk 'NR == 1{print $3 " "$4}')
echo "#LVM use:" $(if [ $(lsblk | grep lvm | wc -l) == 0 ]; then echo no; else echo yes ;fi)
echo "#Connections TCP :" $(ss -s | awk 'NR == 2 { printf "%2.f", $4 }' && echo " ESTABLISHED")
echo "#User log:" $(users | wc -w)
echo "#Network: IP" $(hostname -I && ip address | awk 'NR == 8 {print "(" $2 ")"}')
echo "#Sudo :" $(journalctl -q | grep COMMAND | wc -l && echo "cmd")